ordersexport:
  path: ordersexport/demo
  methods: [GET,POST]
  defaults:
    _controller: 'OrdersExport\Controller\OrdersExportController::printForm'
    _legacy_controller: 'OrdersExportController'
    _legacy_link: 'OrdersExportController'

task_success:
  path: ordersexport/demo
  methods: [GET,POST]
  defaults:
    _controller: 'OrdersExport\Controller\OrdersExportController::printForm'
    _legacy_controller: 'OrdersExportController'
    _legacy_link: 'OrdersExportController'
